projects:
  StockAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-1
        apiId: 7xnoy6qg5jbj5ixmnt2fcom7pe
        maxDepth: 2
extensions:
  amplify:
    version: 3
