// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://7kkdnsp3pfhcbm76da5kf2h2na.appsync-api.us-west-1.amazonaws.com/graphql',
          region: 'us-west-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-czzafpu5xredplaww57cveyhde'
        }
    }
};

export default config;